# Generated by Django 4.1.1 on 2022-09-29 20:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=datetime.datetime.now)),
                ("updated", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1000.0),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(300.0),
                        ],
                    ),
                ),
                (
                    "blood",
                    models.CharField(
                        choices=[("I", "0"), ("II", "A"), ("III", "B"), ("IV", "AB"), ("-", "None")],
                        default="-",
                        max_length=3,
                    ),
                ),
                ("allergies", models.TextField(blank=True)),
            ],
            options={
                "db_table": "medical_card",
            },
        ),
        migrations.CreateModel(
            name="MedicalCardAppointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=datetime.datetime.now)),
                ("updated", models.DateTimeField(default=datetime.datetime.now)),
                ("symptom", models.TextField(blank=True)),
                ("therapy", models.TextField(blank=True)),
                (
                    "appointment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="appointment.appointment"),
                ),
                (
                    "medical_card",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="medcard.medicalcard"),
                ),
            ],
            options={
                "db_table": "medical_card_appointment",
            },
        ),
        migrations.AddField(
            model_name="medicalcard",
            name="appointments",
            field=models.ManyToManyField(through="medcard.MedicalCardAppointment", to="appointment.appointment"),
        ),
        migrations.AddField(
            model_name="medicalcard",
            name="client",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.client"),
        ),
    ]
