version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: server
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery-worker

  db:
    image: postgres:14-alpine
    container_name: postgres_database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5432"

  redis:
    image: redis
    restart: always

  celery-worker:
    restart: always
    build:
      context: .
    container_name: celery-worker
    command: celery -A medical_assistant worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data: