[tool.isort]
line_length = 119
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["django", "rest_framework", "django_filters"]
skip_glob = ["*/migrations/*"]

[tool.black]
    py36 = true
    line-length = 119
    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | ^migrations/
      | venv

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/
    '''