version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web_server
    volumes:
      - ./medical_assistant:/app
    ports:
      - "8000:8000"
    env_file:
      - ./medical_assistant/.env
    depends_on:
      - redis
      - celery-worker
      - pg_db

  pg_db:
    image: postgres:14-alpine
    container_name: database
    env_file:
      - ./medical_assistant/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=assistant_db
      - POSTGRES_USER=medical_user
      - POSTGRES_PASSWORD=medical_assistant
    ports:
      - "5434:5432"

  redis:
    image: redis
    restart: always
    container_name: redis

  celery-worker:
    restart: always
    build:
      context: .
    container_name: celery
    command: celery -A medical_assistant worker -l info
    volumes:
      - ./medical_assistant:/app
    depends_on:
      - redis
    env_file:
      - medical_assistant/.env

volumes:
  postgres_data: