# Generated by Django 4.1.1 on 2022-09-29 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sex",
                    models.CharField(choices=[("M", "Man"), ("W", "Woman"), ("-", "None")], default="-", max_length=1),
                ),
                ("birthday_date", models.DateField(default=datetime.date.today)),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=datetime.datetime.now)),
                ("updated", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "category",
                    models.CharField(
                        choices=[("H", "High"), ("1", "First"), ("2", "Second")], default="2", max_length=1
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("THER", "Therapy"),
                            ("DERM", "Dermatology"),
                            ("GYNE", "Gynecology"),
                            ("SURG", "Surgery"),
                            ("CT", "Children's therapy"),
                            ("NEUR", "Neurology"),
                            ("PSYC", "Psychotherapy"),
                            ("CARD", "Cardiology"),
                            ("ONCO", "Oncology"),
                            ("DENT", "Dentistry"),
                        ],
                        default="THER",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "db_table": "doctor",
            },
        ),
    ]
