# Generated by Django 4.1.3 on 2022-11-13 15:08

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(max_length=500, storage=core.storage_backends.ImageStorage(), upload_to=""),
                ),
            ],
        ),
    ]
