# Generated by Django 4.1.1 on 2022-09-29 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=datetime.datetime.now)),
                ("updated", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "type",
                    models.CharField(
                        choices=[("C", "Consultation"), ("S", "Survey"), ("O", "Operation")], default="C", max_length=1
                    ),
                ),
                ("visiting_datetime", models.DateTimeField(default=datetime.datetime.now)),
                ("approved", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "appointment",
            },
        ),
    ]
